package com.bot.model;

public enum Operation {
    START,
    CITY_SELECTION, CONCERN_SELECTION, BRAND_SELECTION, MODEL_SELECTION, ENGINE_SELECTION,
    NEED_CAR,
    PRE_PHOTO,
    PHOTO,
    DESCRIPTION,
    APPROVED_REQUEST, EDIT_REQUEST, REJECTED_REQUEST,

    END
}
