package com.bot.model;


public enum Operations {
    ERROR,
    //main
    START,   END,
    CITY_SELECTION,
    //car
    CONCERN_SELECTION, BRAND_SELECTION, MODEL_SELECTION, ENGINE_SELECTION, NEED_CAR,
    //photo
    PRE_PHOTO, PHOTO,
    ENTER_PRICE,
    DESCRIPTION,
    //admin
    ENTER_NEW_DESCRIPTION, APPROVED_REQUEST, EDIT_REQUEST, EDIT_DESCRIPTION, ADMIN_EDIT_CAR, REJECTED_REQUEST, SEND_REJECTED_REQUEST,
    DELETE_ENGINE, DELETE_CAR, DELETE_BRAND, DELETE_MODEL,
    //cabinet
    EDIT_CAR, EDIT_USER, MY_ACCOMMODATION
}
